version: '3.8'

services:
  # Serviço do MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  # Serviço do Kafka
  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
    networks:
      - app_network

  # Serviço do Zookeeper (necessário para o Kafka)
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
    ports:
      - "2181:2181"
    networks:
      - app_network

  # Serviço do Neo4j
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - app_network

  # Serviço do seu aplicativo Python com Streamlit
  app:
    build: .
    container_name: recommendation_app
    ports:
      - "8501:8501"
    depends_on:
      - mongodb
      - kafka
      - neo4j
    networks:
      - app_network

# Definição de volumes persistentes
volumes:
  mongodb_data:

# Definição das redes
networks:
  app_network:
    driver: bridge
